/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#1b1c1a',
        'on-tertiary-fixed-variant': '#772e3e',
        'on-secondary-container': '#745c00',
        'surface-container-low': '#f5f3f0',
        'surface-container-high': '#eae8e5',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#30312f',
        outline: '#867276',
        'surface-variant': '#e4e2df',
        'on-background': '#1b1c1a',
        background: '#fbf9f6',
        error: '#ba1a1a',
        'outline-variant': '#d8c1c4',
        surface: '#fbf9f6',
        'surface-tint': '#95435b',
        'primary-fixed': '#ffd9e0',
        'surface-dim': '#dbdad7',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#f2f0ed',
        'on-secondary-fixed-variant': '#574500',
        'on-surface-variant': '#534246',
        tertiary: '#3f0215',
        'primary-fixed-dim': '#ffb1c3',
        'tertiary-fixed': '#ffd9de',
        'on-primary-fixed-variant': '#782c44',
        'tertiary-container': '#5b1829',
        'surface-container': '#efeeeb',
        'on-tertiary-fixed': '#3e0215',
        'inverse-primary': '#ffb1c3',
        secondary: '#735c00',
        'on-primary-container': '#db7c95',
        'surface-container-highest': '#e4e2df',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#ffb2be',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#ffe088',
        'secondary-fixed-dim': '#e9c349',
        'on-tertiary-container': '#da7e8e',
        'primary-container': '#5c162e',
        'on-primary-fixed': '#3f0019',
        'surface-bright': '#fbf9f6',
        'secondary-container': '#fed65b',
        primary: '#400019',
        'on-secondary-fixed': '#241a00',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        'display-mobile': ['"Playfair Display"', 'serif'],
        'headline-lg': ['"Playfair Display"', 'serif'],
        'headline-lg-mobile': ['"Playfair Display"', 'serif'],
        'headline-md': ['"Playfair Display"', 'serif'],
        'headline-sm': ['"Playfair Display"', 'serif'],
        title: ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '500' }],
        title: ['18px', { lineHeight: '26px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.04em', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '500' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '600' }],
        display: ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '600' }],
        'headline-sm': ['22px', { lineHeight: '30px', fontWeight: '500' }],
        'display-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
};
